### PR TITLE
GRIB format

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@martindurant , why not just pass the filter options (e.g. `'filter_by_keys': {'typeOfLevel': 'heightAboveGround', 'level': 2}` when you [create the dataset](https://github.com/intake/fsspec-reference-maker/pull/27/files#diff-d2ae1eb3f34de6be154634a093d6cc43fbd0b20defad05e298c4a6f1b76eeb97R95) instead of the [logic here](https://github.com/intake/fsspec-reference-maker/pull/27/files#diff-d2ae1eb3f34de6be154634a093d6cc43fbd0b20defad05e298c4a6f1b76eeb97R96-R125)?

(I tried using a filter `'filter_by_keys': {'typeOfLevel': 'surface'}` to get all the surface variables and it failed because the logic was expecting to find a layer value)

**Comment by martindurant** [comment]
I made it specific to the case in front of me. 
To get al the levels, you would need another dimension and to find all the values for that dimension's coordinates. Perhaps this isn't too bad, I'll have a look.

**Comment by rsignell-usgs** [comment]
@martindurant, the `'filter_by_keys': {'typeOfLevel': 'surface'}` syntax actually pulls all the variables that exist at the surface of the earth, not at different levels (there is no level=0 in this dataset).  These are really just filtering the info that follows the short variable name in the GRIB records:
```
rsignell-usgs@jupyter-rsignell-2dusgs:~/shared/users/rsignell/notebooks/HRRR/tmp$ wgrib2 9f2c4c75d724bc7af82e2a631421adfc8ffbc9cde3c66a21698e3a634c68c2d0
1:0:d=2019010114:REFC:entire atmosphere:1 hour fcst:
2:435356:d=2019010114:RETOP:cloud top:1 hour fcst:
3:556196:d=2019010114:VIL:entire atmosphere:1 hour fcst:
4:898688:d=2019010114:VIS:surface:1 hour fcst:
5:2236194:d=2019010114:REFD:1000 m above ground:1 hour fcst:
6:2443435:d=2019010114:REFD:4000 m above ground:1 hour fcst:
7:2553056:d=2019010114:REFD:263 K level:1 hour fcst:
8:2737525:d=2019010114:GUST:surface:1 hour fcst:
9:4005320:d=2019010114:UGRD:250 mb:1 hour fcst:
10:4742258:d=2019010114:VGRD:250 mb:1 hour fcst:
11:5448327:d=2019010114:UGRD:300 mb:1 hour fcst:
12:6185335:d=2019010114:VGRD:300 mb:1 hour fcst:
13:6895757:d=2019010114:HGT:500 mb:1 hour fcst:
14:7615448:d=2019010114:TMP:500 mb:1 hour fcst:
15:8167381:d=2019010114:DPT:500 mb:1 hour fcst:
16:9062723:d=2019010114:UGRD:500 mb:1 hour fcst:
17:9659063:d=2019010114:VGRD:500 mb:1 hour fcst:
18:10238778:d=2019010114:HGT:700 mb:1 hour fcst:
19:10958148:d=2019010114:TMP:700 mb:1 hour fcst:
20:11523638:d=2019010114:DPT:700 mb:1 hour fcst:
21:12513597:d=2019010114:UGRD:700 mb:1 hour fcst:
22:13122919:d=2019010114:VGRD:700 mb:1 hour fcst:
23:13719401:d=2019010114:HGT:850 mb:1 hour fcst:
24:14489517:d=2019010114:TMP:850 mb:1 hour fcst:
25:15102242:d=2019010114:DPT:850 mb:1 hour fcst:
26:16210170:d=2019010114:UGRD:850 mb:1 hour fcst:
27:16853689:d=2019010114:VGRD:850 mb:1 hour fcst:
28:17482460:d=2019010114:TMP:925 mb:1 hour fcst:
29:18110325:d=2019010114:DPT:925 mb:1 hour fcst:
30:19217759:d=2019010114:UGRD:925 mb:1 hour fcst:
31:19859569:d=2019010114:VGRD:925 mb:1 hour fcst:
32:20504374:d=2019010114:TMP:1000 mb:1 hour fcst:
33:21149284:d=2019010114:DPT:1000 mb:1 hour fcst:
34:22250237:d=2019010114:UGRD:1000 mb:1 hour fcst:
35:22896712:d=2019010114:VGRD:1000 mb:1 hour fcst:
36:23529329:d=2019010114:MAXUVV:100-1000 mb above ground:0-1 hour max fcst:
37:24178629:d=2019010114:MAXDVV:100-1000 mb above ground:0-1 hour max fcst:
38:24851859:d=2019010114:DZDT:0.5-0.8 sigma layer:0-1 hour ave fcst:
39:25622894:d=2019010114:MSLMA:mean sea level:1 hour fcst:
40:26275171:d=2019010114:HGT:1000 mb:1 hour fcst:
41:27088489:d=2019010114:MAXREF:1000 m above ground:0-1 hour max fcst:
42:27610933:d=2019010114:REFD:263 K level:0-1 hour max fcst:
43:27812445:d=2019010114:MXUPHL:5000-2000 m above ground:0-1 hour max fcst:
44:28025734:d=2019010114:MNUPHL:5000-2000 m above ground:0-1 hour min fcst:
45:28261156:d=2019010114:MXUPHL:2000-0 m above ground:0-1 hour max fcst:
46:28355457:d=2019010114:MNUPHL:2000-0 m above ground:0-1 hour min fcst:
47:28818434:d=2019010114:MXUPHL:3000-0 m above ground:0-1 hour max fcst:
48:28954960:d=2019010114:MNUPHL:3000-0 m above ground:0-1 hour min fcst:
49:29417937:d=2019010114:RELV:2000-0 m above ground:0-1 hour max fcst:
50:31360812:d=2019010114:RELV:1000-0 m above ground:0-1 hour max fcst:
51:33682238:d=2019010114:HAIL:entire atmosphere:0-1 hour max fcst:
52:33803527:d=2019010114:HAIL:0.1 sigma level:0-1 hour max fcst:
53:33870943:d=2019010114:TCOLG:entire atmosphere (considered as a single layer):0-1 hour max fcst:
54:33883161:d=2019010114:LTNG:entire atmosphere:1 hour fcst:
55:33883349:d=2019010114:UGRD:80 m above ground:1 hour fcst:
56:35066013:d=2019010114:VGRD:80 m above ground:1 hour fcst:
57:36250167:d=2019010114:PRES:surface:1 hour fcst:
58:37848386:d=2019010114:HGT:surface:1 hour fcst:
59:40083163:d=2019010114:TMP:surface:1 hour fcst:
60:41532778:d=2019010114:ASNOW:surface:0-1 hour acc fcst:
61:41899752:d=2019010114:MSTAV:0 m underground:1 hour fcst:
62:43121948:d=2019010114:CNWAT:surface:1 hour fcst:
63:43455440:d=2019010114:WEASD:surface:1 hour fcst:
64:44376419:d=2019010114:SNOWC:surface:1 hour fcst:
65:44518253:d=2019010114:SNOD:surface:1 hour fcst:
66:45250738:d=2019010114:TMP:2 m above ground:1 hour fcst:
67:46518091:d=2019010114:POT:2 m above ground:1 hour fcst:
68:47693584:d=2019010114:SPFH:2 m above ground:1 hour fcst:
69:48918125:d=2019010114:DPT:2 m above ground:1 hour fcst:
70:50085363:d=2019010114:RH:2 m above ground:1 hour fcst:
71:51644784:d=2019010114:UGRD:10 m above ground:1 hour fcst:
72:52882909:d=2019010114:VGRD:10 m above ground:1 hour fcst:
73:54111788:d=2019010114:WIND:10 m above ground:0-1 hour max fcst:
74:55373752:d=2019010114:MAXUW:10 m above ground:0-1 hour max fcst:
75:56731296:d=2019010114:MAXVW:10 m above ground:0-1 hour max fcst:
76:58074500:d=2019010114:CPOFP:surface:1 hour fcst:
77:58186795:d=2019010114:PRATE:surface:1 hour fcst:
78:58241942:d=2019010114:APCP:surface:0-1 hour acc fcst:
79:58792371:d=2019010114:WEASD:surface:0-1 hour acc fcst:
80:59157846:d=2019010114:FROZR:surface:0-1 hour acc fcst:
81:59249464:d=2019010114:FRZR:surface:0-1 hour acc fcst:
82:59388905:d=2019010114:SSRUN:surface:0-1 hour acc fcst:
83:59394970:d=2019010114:BGRUN:surface:0-1 hour acc fcst:
84:59395289:d=2019010114:CSNOW:surface:1 hour fcst:
85:59432166:d=2019010114:CICEP:surface:1 hour fcst:
86:59433630:d=2019010114:CFRZR:surface:1 hour fcst:
87:59445143:d=2019010114:CRAIN:surface:1 hour fcst:
88:59506167:d=2019010114:SFCR:surface:1 hour fcst:
89:61348656:d=2019010114:FRICV:surface:1 hour fcst:
90:62585565:d=2019010114:SHTFL:surface:1 hour fcst:
91:63917139:d=2019010114:LHTFL:surface:1 hour fcst:
92:65152344:d=2019010114:GFLUX:surface:1 hour fcst:
93:65691518:d=2019010114:VGTYP:surface:1 hour fcst:
94:66473088:d=2019010114:LFTX:500-1000 mb:1 hour fcst:
95:67430691:d=2019010114:CAPE:surface:1 hour fcst:
96:67680693:d=2019010114:CIN:surface:1 hour fcst:
97:67981080:d=2019010114:PWAT:entire atmosphere (considered as a single layer):1 hour fcst:
98:68743762:d=2019010114:LCDC:low cloud layer:1 hour fcst:
99:69459550:d=2019010114:MCDC:middle cloud layer:1 hour fcst:
100:69799090:d=2019010114:HCDC:high cloud layer:1 hour fcst:
101:70068181:d=2019010114:TCDC:entire atmosphere:1 hour fcst:
102:70865936:d=2019010114:PRES:cloud base:1 hour fcst:
103:71795172:d=2019010114:HGT:cloud base:1 hour fcst:
104:73370228:d=2019010114:HGT:cloud ceiling:1 hour fcst:
105:75203377:d=2019010114:PRES:cloud top:1 hour fcst:
106:76129612:d=2019010114:HGT:cloud top:1 hour fcst:
107:77906558:d=2019010114:ULWRF:top of atmosphere:1 hour fcst:
108:79857374:d=2019010114:DSWRF:surface:1 hour fcst:
109:81657563:d=2019010114:DLWRF:surface:1 hour fcst:
110:83721328:d=2019010114:USWRF:surface:1 hour fcst:
111:85052163:d=2019010114:ULWRF:surface:1 hour fcst:
112:86844287:d=2019010114:VBDSF:surface:1 hour fcst:
113:88479055:d=2019010114:VDDSF:surface:1 hour fcst:
114:90336621:d=2019010114:USWRF:top of atmosphere:1 hour fcst:
115:92085841:d=2019010114:HLCY:3000-0 m above ground:1 hour fcst:
116:93392245:d=2019010114:HLCY:1000-0 m above ground:1 hour fcst:
117:94668534:d=2019010114:USTM:0-6000 m above ground:1 hour fcst:
118:95688465:d=2019010114:VSTM:0-6000 m above ground:1 hour fcst:
119:96663042:d=2019010114:VUCSH:0-1000 m above ground:1 hour fcst:
120:97974646:d=2019010114:VVCSH:0-1000 m above ground:1 hour fcst:
121:99291109:d=2019010114:VUCSH:0-6000 m above ground:1 hour fcst:
122:100493464:d=2019010114:VVCSH:0-6000 m above ground:1 hour fcst:
123:101678778:d=2019010114:HGT:0C isotherm:1 hour fcst:
124:103375348:d=2019010114:RH:0C isotherm:1 hour fcst:
125:104214249:d=2019010114:PRES:0C isotherm:1 hour fcst:
126:105230344:d=2019010114:HGT:highest tropospheric freezing level:1 hour fcst:
127:105917488:d=2019010114:RH:highest tropospheric freezing level:1 hour fcst:
128:106732957:d=2019010114:PRES:highest tropospheric freezing level:1 hour fcst:
129:107699811:d=2019010114:HGT:263 K level:1 hour fcst:
130:108501658:d=2019010114:HGT:253 K level:1 hour fcst:
131:109217635:d=2019010114:4LFTX:180-0 mb above ground:1 hour fcst:
132:110227532:d=2019010114:CAPE:180-0 mb above ground:1 hour fcst:
133:110526611:d=2019010114:CIN:180-0 mb above ground:1 hour fcst:
134:110822565:d=2019010114:HPBL:surface:1 hour fcst:
135:113654669:d=2019010114:HGT:level of adiabatic condensation from sfc:1 hour fcst:
136:116415033:d=2019010114:CAPE:90-0 mb above ground:1 hour fcst:
137:116630237:d=2019010114:CIN:90-0 mb above ground:1 hour fcst:
138:116924499:d=2019010114:CAPE:255-0 mb above ground:1 hour fcst:
139:117171953:d=2019010114:CIN:255-0 mb above ground:1 hour fcst:
140:117460853:d=2019010114:HGT:equilibrium level:1 hour fcst:
141:119554218:d=2019010114:PLPL:255-0 mb above ground:1 hour fcst:
142:120582911:d=2019010114:RHPW:entire atmosphere:1 hour fcst:
143:121654945:d=2019010114:LAND:surface:1 hour fcst:
144:121705421:d=2019010114:ICEC:surface:1 hour fcst:
145:121723121:d=2019010114:SBT123:top of atmosphere:1 hour fcst:
146:123292190:d=2019010114:SBT124:top of atmosphere:1 hour fcst:
147:124901318:d=2019010114:SBT113:top of atmosphere:1 hour fcst:
148:126317719:d=2019010114:SBT114:top of atmosphere:1 hour fcst:
```

**Comment by martindurant** [comment]
How do I reconcile the following two "surface" variables:
```
{'GRIB_paramId': 260056, 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': 1905141, 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': 1, 'GRIB_stepType': 'instant', 'GRIB_gridType': 'lambert', 'GRIB_DxInMetres': 3000.0, 'GRIB_DyInMetres': 3000.0, 'GRIB_LaDInDegrees': 38.5, 'GRIB_Latin1InDegrees': 38.5, 'GRIB_Latin2InDegrees': 38.5, 'GRIB_LoVInDegrees': 262.5, 'GRIB_NV': 0, 'GRIB_Nx': 1799, 'GRIB_Ny': 1059, 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'sdwe', 'GRIB_gridDefinitionDescription': 'Lambert Conformal can be secant or tangent, conical or bipolar', 'GRIB_iScansNegatively': 0, 'GRIB_jPointsAreConsecutive': 0, 'GRIB_jScansPositively': 1, 'GRIB_latitudeOfFirstGridPointInDegrees': 21.138123, 'GRIB_latitudeOfSouthernPoleInDegrees': 0.0, 'GRIB_longitudeOfFirstGridPointInDegrees': 237.280472, 'GRIB_longitudeOfSouthernPoleInDegrees': 0.0, 'GRIB_missingValue': 9999, 'GRIB_name': 'Water equivalent of accumulated snow depth (deprecated)', 'GRIB_shortName': 'sdwe', 'GRIB_units': 'kg m**-2', 'long_name': 'Water equivalent of accumulated snow depth (deprecated)', 'units': 'kg m**-2', 'standard_name': 'unknown', 'coordinates': 'time step surface latitude longitude valid_time'} Variable(dimensions=('y', 'x'), data=OnDiskArray(stream=FileStream(path='/var/folders/37/tv8hwzgx3tjgtbn0lsb6vrdc0000gp/T/tmpwq68kg4cgrib2', errors='warn'), shape=(1059, 1799), missing_value=9999))
{'GRIB_paramId': 260056, 'GRIB_dataType': 'fc', 'GRIB_numberOfPoints': 1905141, 'GRIB_typeOfLevel': 'surface', 'GRIB_stepUnits': 1, 'GRIB_stepType': 'accum', 'GRIB_gridType': 'lambert', 'GRIB_DxInMetres': 3000.0, 'GRIB_DyInMetres': 3000.0, 'GRIB_LaDInDegrees': 38.5, 'GRIB_Latin1InDegrees': 38.5, 'GRIB_Latin2InDegrees': 38.5, 'GRIB_LoVInDegrees': 262.5, 'GRIB_NV': 0, 'GRIB_Nx': 1799, 'GRIB_Ny': 1059, 'GRIB_cfName': 'unknown', 'GRIB_cfVarName': 'sdwe', 'GRIB_gridDefinitionDescription': 'Lambert Conformal can be secant or tangent, conical or bipolar', 'GRIB_iScansNegatively': 0, 'GRIB_jPointsAreConsecutive': 0, 'GRIB_jScansPositively': 1, 'GRIB_latitudeOfFirstGridPointInDegrees': 21.138123, 'GRIB_latitudeOfSouthernPoleInDegrees': 0.0, 'GRIB_longitudeOfFirstGridPointInDegrees': 237.280472, 'GRIB_longitudeOfSouthernPoleInDegrees': 0.0, 'GRIB_missingValue': 9999, 'GRIB_name': 'Water equivalent of accumulated snow depth (deprecated)', 'GRIB_shortName': 'sdwe', 'GRIB_units': 'kg m**-2', 'long_name': 'Water equivalent of accumulated snow depth (deprecated)', 'units': 'kg m**-2', 'standard_name': 'unknown', 'coordinates': 'time step surface latitude longitude valid_time'} Variable(dimensions=('y', 'x'), data=OnDiskArray(stream=FileStream(path='/var/folders/37/tv8hwzgx3tjgtbn0lsb6vrdc0000gp/T/tmpncv82vgpgrib2', errors='warn'), shape=(1059, 1799), missing_value=9999))
```

(one is "instant", one is "accum" - but they share the same coordinates and variable name, so would stomp on each other)

**Comment by martindurant** [comment]
By the way, the value for the surface variables is indeed 0:
```
> ds.variables['surface']
Variable(dimensions=(), data=0.0)
```
so the original syntax would have worked here, except for the overlapping variables issue above. 

I'd also like to make it for for heightAboveGround to make an array so that you can select from all heights in the final dataset. Is there any way to know before scanning all the data what values one of these attributes can have?

**Comment by martindurant** [comment]
^ or could that be an input from the user:
`filter={'typeOfLevel': 'heightAboveGround', 'level': [2, 10, 80, 1000, 4000]}`

**Comment by rsignell-usgs** [comment]
It's interesting that the cfgrib library says it uses https://github.com/ecmwf/eccodes-python and on that page the "usage" points to https://confluence.ecmwf.int/display/ECC/Documentation, which contains [this interesting page](https://confluence.ecmwf.int/display/UDOC/How+do+I+use+an+OR+condition+%28logical+disjunction%29+in+a+where+clause+-+ecCodes+GRIB+FAQ) about how to do "OR" "AND".   

There it says you can do `grib_get -w level=100/150/200` but when tried that in cfgrib it failed.

**Comment by rsignell-usgs** [comment]
To answer your question about the two vars that have the same name and the same level they have different step types:
GRIB_stepType': 'instant', 'GRIB_stepType': 'accum'.

FWIW, here is how Unidata decodes the HRRR GRIB2 into the NetCDF data model:
https://thredds-jumbo.unidata.ucar.edu/thredds/dodsC/grib/NCEP/HRRR/CONUS_2p5km/HRRR_CONUS_2p5km_20210601_0000.grib2.html

**Comment by rsignell-usgs** [comment]
Unidata solved this by giving the variables very long names like: 
`Total_precipitation_surface_1_Hour_Accumulation`

**Comment by rsignell-usgs** [comment]
@martindurant , I tested the version of `hdf.py` here on the NWM data and it still works.   Should we accept this PR and move on?

**Pull request merged**
